# Generated by Django 5.0 on 2024-01-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Phone', models.IntegerField()),
                ('SP', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=240, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
