# Generated by Django 5.0 on 2024-01-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_nurse_doctor_email_doctor_password_patient_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appoiment',
            new_name='Appointment',
        ),
    ]
